name: flutter_form_generator
description: "A new Flutter package project."
version: 0.0.1
repository: https://github.com/LifeScheduler/flutter_form_generator
issue_tracker: https://github.com/LifeScheduler/flutter_form_generator/issues
homepage: https://github.com/LifeScheduler

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - forms
  - code-generation
  - models